name: Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'main.md'  # 仅在 main.md 文件更改时触发

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装 Pandoc
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # 安装 LaTeX
      - name: Install LaTeX
        run: sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      # 将 main.md 转换为 main.tex
      - name: Convert Markdown to LaTeX
        run: pandoc -s main.md -o main.tex

      # 将 main.tex 编译为 main.pdf
#      - name: Compile LaTeX to PDF
#        run: pdflatex main.tex

      # 将生成的 PDF 文件提交回仓库
      - name: Commit PDF to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add main.tex
          git commit -m "Auto-generated PDF from main.md"
          git push
